// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnJqiDAaIahNtQCKACQIiKvlDH4HhNYDA',
    appId: '1:292872685738:web:9b08023ca11a4b10d6a8d3',
    messagingSenderId: '292872685738',
    projectId: 'lifeguardian-app',
    authDomain: 'lifeguardian-app.firebaseapp.com',
    storageBucket: 'lifeguardian-app.firebasestorage.app',
    measurementId: 'G-MVSK24CGDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf6X97VndzFK1K6V1RibLEWpcgPpobdg8',
    appId: '1:292872685738:android:0e5d178179f9baefd6a8d3',
    messagingSenderId: '292872685738',
    projectId: 'lifeguardian-app',
    storageBucket: 'lifeguardian-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9qxbNlv-Dy0LQ5TDqn14lgoVQta2pKaM',
    appId: '1:292872685738:ios:84c1ea1cd00e3db5d6a8d3',
    messagingSenderId: '292872685738',
    projectId: 'lifeguardian-app',
    storageBucket: 'lifeguardian-app.firebasestorage.app',
    androidClientId: '292872685738-6ot8uu0g5u27seulvjgc6tub0ujgtbn4.apps.googleusercontent.com',
    iosClientId: '292872685738-s8muujp6hdv453lpknjakpa8cr4m3q9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifeguardian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9qxbNlv-Dy0LQ5TDqn14lgoVQta2pKaM',
    appId: '1:292872685738:ios:84c1ea1cd00e3db5d6a8d3',
    messagingSenderId: '292872685738',
    projectId: 'lifeguardian-app',
    storageBucket: 'lifeguardian-app.firebasestorage.app',
    androidClientId: '292872685738-6ot8uu0g5u27seulvjgc6tub0ujgtbn4.apps.googleusercontent.com',
    iosClientId: '292872685738-s8muujp6hdv453lpknjakpa8cr4m3q9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifeguardian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvIyrRgCtCVEsOUtbgLTwM3Qn30sA8yOo',
    appId: '1:292872685738:web:ea8231fc869a422ad6a8d3',
    messagingSenderId: '292872685738',
    projectId: 'lifeguardian-app',
    authDomain: 'lifeguardian-app.firebaseapp.com',
    storageBucket: 'lifeguardian-app.firebasestorage.app',
    measurementId: 'G-KJGGK5QS1E',
  );

}